// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.reservationsystem.domain;

import com.se.reservationsystem.domain.DurableArticles;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DurableArticles_Roo_Configurable {
    
    declare @type: DurableArticles: @Configurable;
    
}
