// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se.reservationsystem.domain;

import com.se.reservationsystem.domain.DurableArticles;

privileged aspect DurableArticles_Roo_JavaBean {
    
    public String DurableArticles.getName() {
        return this.name;
    }
    
    public void DurableArticles.setName(String name) {
        this.name = name;
    }
    
}
